-- Um banco compartilhado, com um schema isolado para cada servico.
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION sabia;
CREATE SCHEMA IF NOT EXISTS pedagogico AUTHORIZATION sabia;

GRANT USAGE, CREATE ON SCHEMA auth TO sabia;
GRANT USAGE, CREATE ON SCHEMA pedagogico TO sabia;

ALTER ROLE sabia SET search_path TO auth, public;

ALTER DEFAULT PRIVILEGES FOR ROLE sabia IN SCHEMA auth
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sabia;
ALTER DEFAULT PRIVILEGES FOR ROLE sabia IN SCHEMA auth
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO sabia;
ALTER DEFAULT PRIVILEGES FOR ROLE sabia IN SCHEMA pedagogico
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sabia;
ALTER DEFAULT PRIVILEGES FOR ROLE sabia IN SCHEMA pedagogico
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO sabia;