spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    com.sabia: DEBUG
    org.springframework.web: DEBUG
